// <auto-generated/>
namespace Core.Localization
{
    public static class SharedText
    {
        public static readonly TextKey Play = new("Shared", "play");
        public static readonly TextKey Settings = new("Shared", "settings");
        public static readonly TextKey Quit = new("Shared", "quit");
        public static readonly TextKey Back = new("Shared", "back");
        public static readonly TextKey Version = new("Shared", "version");
        public static readonly TextKey Language = new("Shared", "language");
        public static readonly TextKey MasterVolume = new("Shared", "master_volume");
        public static readonly TextKey MusicVolume = new("Shared", "music_volume");
        public static readonly TextKey SfxVolume = new("Shared", "sfx_volume");
        public static readonly TextKey UiVolume = new("Shared", "ui_volume");
    }
}
