// <auto-generated/>
namespace Core.Localization
{
    public static class SharedText
    {
        public static readonly TextKey Play = new("Shared", "play");
        public static readonly TextKey Settings = new("Shared", "settings");
        public static readonly TextKey Quit = new("Shared", "quit");
        public static readonly TextKey Resume = new("Shared", "resume");
        public static readonly TextKey QuitToMenu = new("Shared", "quit_to_menu");
        public static readonly TextKey Back = new("Shared", "back");
        public static readonly TextKey Paused = new("Shared", "paused");
        public static readonly TextKey Version = new("Shared", "version");
        public static readonly TextKey Language = new("Shared", "language");
        public static readonly TextKey MasterVolume = new("Shared", "master_volume");
        public static readonly TextKey MusicVolume = new("Shared", "music_volume");
        public static readonly TextKey SfxVolume = new("Shared", "sfx_volume");
        public static readonly TextKey UiVolume = new("Shared", "ui_volume");
        public static readonly TextKey Score = new("Shared", "score");
        public static readonly TextKey TimeLeft = new("Shared", "time_left");
        public static readonly TextKey BestScore = new("Shared", "best_score");
        public static readonly TextKey YouWon = new("Shared", "you_won");
        public static readonly TextKey YouLost = new("Shared", "you_lost");
        public static readonly TextKey PlayAgain = new("Shared", "play_again");
    }
}
